const types = {
    FETCH_DETAILS: "FETCH_DETAILS",
    FETCH_ALL: "FETCH_ALL",
    FETCH_SINGLE: "FETCH_SINGLE",
    FETCH_ITEM_DETAILS: "FETCH_ITEM_DETAILS",
    ADD_BASKET: "ADD_BASKET",
    UPDATE_BASKET: "UPDATE_BASKET",
    LOADING_DONE: "LOADING_DONE",
    SORT: "SORT"
}

export default types;
